version: 2.1 jobs: build: docker:

      - image: alpine:3.7
    steps:
      - run:
          name: 最初のステップ
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
            name: テスト用
            type: approval
            command: |
            echo 'test test'
                  
